openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    Atividade referente plataforma de pagamento Pix.

  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://pix.swagger.io/api/v3
tags:
  - name: pix
    description: Everything about your Pix
    externalDocs:
      description: Find out more
      url: http://swagger.io

paths:
  /enviaPix:
   post:
      tags:
        - pix
      summary: Cria um novo lancamento de pix
      description: Cria um novo lancamento de pix
      operationId: addPix
      requestBody:
        description: Cria um novo lancamento de pix
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pix'
          application/xml:
            schema:
              $ref: '#/components/schemas/Pix'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pix'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pix'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Pix'
        '405':
          description: Invalid input
      security:
        - pixstore_auth:
            - write:pix
            - read:pix
            
          
  /criaChavePix:
    post:
      tags:
        - pix
      summary: Cria uma nova chave pix
      description: This can only be done by the logged in user.
      operationId: createChavePix
      requestBody:
        description: Cria uma nova chave pix
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChavePix'
          application/xml:
            schema:
              $ref: '#/components/schemas/ChavePix'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ChavePix'
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChavePix'
            application/xml:
              schema:
                $ref: '#/components/schemas/ChavePix'
          
  /consultaChavePix/{pixChave}:
    get:
      tags:
        - pix
      summary: Consulta dados de chave Pix existente
      description: Returna dados bancarios de uma chave
      operationId: getPixByChave
      parameters:
        - name: pixChave
          in: path
          description: ID para envio do pix
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChavePix'          
            application/xml:
              schema:
                $ref: '#/components/schemas/ChavePix'
        '400':
          description: Chave Pix invalida
        '404':
          description: Chave Pix nao encontrada
      security:
        - api_key: []
        - pixstore_auth:
            - write:pix
            - read:pix
            
  /deletaChavePix/{pixChave}:        
    delete:
      tags:
        - pix
      summary: Deleta uma chave pix existente
      description: delete uma chave pix
      operationId: deleteChavePix
      parameters:
        - name: api_key
          in: header
          description: ''
          required: false
          schema:
            type: string
        - name: pixChave
          in: path
          description: Chave pix para delete
          required: true
          schema:
            type: string
      responses:
        '400':
          description: Chave Pix Invalida
      security:
        - pixstore_auth:
            - write:pix
            - read:pix
            
 
components:
  schemas:
    Pix:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        chavePix:
          type: string
          example: 1199887766
        pixDate:
          type: string
          format: date-time
        pixStatus:
          type: string
          description: Status do pix realizado
          example: pendente
          enum:
            - enviado
            - pendente
            - rejeitado
        pixValor:
          type: integer
          format: int64
          example: 1000

      xml:
        name: pix
        
    ChavePix:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100000
        chavePix:
          type: string
          example: 1199887766
        nome:
          type: string
          example: josedasilva
        banco:
          type: string
          example: banco do brasil
        agencia:
          type: string
          example: 001
        contaCorrente:
          type: string
          example: 12345-x
          
      xml:
        name: chavepix
    

  securitySchemes:
    pixstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://pix.swagger.io/oauth/authorize
          scopes:
            write:pix: modify pix in your account
            read:pix: read your pix
    api_key:
      type: apiKey
      name: api_key
      in: header
